require:
  - rubocop-performance
  - rubocop-rails

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
   - "vendor/**/*" # rubocop config/default.yml
   - "db/**/*"
   - "config/**/*"
   - "bin/*"
   - "node_modules/**/*"
   - "Gemfile"

# メソッドの行数が多すぎないかをチェック
Metrics/MethodLength:
  Max: 30

# Assignment: 変数への代入
# Branch: メソッド呼び出し
# Condition: 条件文
# 上記項目をRubocopが計算して基準値を超えると警告を出す（上記頭文字をとって'Abc'）
Metrics/AbcSize:
  Max: 50
